Tickets/infra 219
Subaru-PFS/doc pull request #24
Opened 2018-08-29 14:08 UTC by hassanxp

2018-09-01 00:54 UTC, yukimoritani requested changes
I'd like to suggest proper categories for some documents.

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000040-01", "Notes on geometry of fiber slit", "Jim Gunn", "", "2012-01-07", "Notes on the geometry of the fiber slit"
Category : SPS
(Fiber slit is a spectrograph component)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000050-01", "Notes on dither", "Jim Gunn", "", "2012-05-17", "Notes on the requirements for the dither mechanism for the FSA"
Category : SPS
(This paper discusses "slit" dithering, not dithering on the sky.)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000060-01", "Notes on aiming fibers", "Jim Gunn", "", "2013-09-12", "Notes on aiming the fibers to create a fiber pupil in the right place (on the gratings) AND the detailed geometry for
Category : SPS
(This paper discusses spectrograph design)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000070-01", "Notes on the formation of ghosts by glass slit plate", "Jim Gunn", "", "2012-09-10", "Notes on the formation of ghosts by a glass slit plate"
Category : SPS
(This paper discusses fiber slit design)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000080-01", "Fiber In/Out", "Jim Gunn", "", "2012-08-22", "Notes on aiming the fibers to create a fiber pupil in the right place (on the gratings) AND the detailed geometry for the PFS sl
Category : FIB
(This paper discusses the entire fiber system. That is, not only Cobra-side, but also Spectrograph-side.)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-FIB-PRU000120-01", "Crosstalk", "Jim Gunn", "", "2013-03-21", "A proposed definition of fiber-to-fiber crosstalk and a proposed specification"
Category : SPS
(This paper discusses spectrograph design.)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000140-01", "Back Illumination", "Jim Gunn", "", "2013-04-16", "A small study on what illumination level is needed for the fiber back-illumination."
Category : GEN?
Back illumination relates with both PFI (fiducial fibers) and SpS (science fibers), so I think "general" would be proper... what do you think of it?

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000150-01", "Slit and Detectors", "Jim Gunn", "", "2013-09-11", "A document detailing the layout of the fibers along the fiber slit. Use in conjuction with the fiber routing white paper,
Category : SPS
(This discusses spectrograph design)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000160-01", "Slit Curvature", "Jim Gunn", "", "2013-08-07", "A small study on the effects of slit curvature on image performance metrics in the presence of FRD"
Category : SPS
(This discusses spectrograph design)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000200-01", "Slit 2 FRD", "Jim Gunn", "", "2015-12-07", "Evaluation of LNA Slit 2 performance (without cover plate)"
Category : SPS
(This discusses analysis of the fiber slit test)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000220-01", "IR Thermal Background", "Jim Gunn", "", "2017-08-02", "The Thermal Background in the PFS IR Dewar"
Category : SPS
(This discusses NIR camera design.)

2018-09-01 00:54 UTC, yukimoritani commented on registries/princeton/documents.csv
> +"PFS-PFI-PRU000230-01", "COBRA and FIDUCIAL Coordinates and Numbering Scheme", "Jim Gunn", "", "2017-11-14", "The COBRA and FIDUCIAL Coordinates and Numbering Scheme"
Category : FIB
(This discusses fiber mapping.)

2018-09-13 21:31 UTC, hassanxp commented
I have implemented all your suggested changes. Ok to merge the PR?

2018-09-13 22:47 UTC, yukimoritani approved these changes

2018-09-13 22:57 UTC, merged