Tickets/infra 227
Subaru-PFS/doc pull request #33
Opened 2019-05-02 05:26 UTC by yukimoritani

2019-05-13 18:26 UTC, naoyukitamura requested changes
Requirements and recommendations to summary and description when a ticket is filed are well written. As well as these, comments to be given when a review is requested and a ticket is closed need to be equally informative (e.g. how test is done, what result(s) is output and why it is satisfactory). So it would be important to write requirements/recommendations somewhere in this procedure. 

Apart from it, I would agree this document is well shaped.

2019-07-09 21:49 UTC, hassanxp commented on development-management/developement_practice.rst
> +PFS Software Developement Practice
Developement -> Development

2019-07-09 21:52 UTC, hassanxp commented on development-management/developement_practice.rst
> +Coding Standars
Standars -> Standards

2019-07-09 21:54 UTC, hassanxp commented on development-management/developement_practice.rst
> +`RES-SYS-1103 <https://sumire.pbworks.com/w/page/76623143/REQ%20SYS%201103>`_ describes the requirement of the comutar language used for the PFS project:
comutar -> computer (or better 'software'?)

2019-07-09 21:57 UTC, hassanxp commented on development-management/developement_practice.rst
> +`REQ SYS 458 <https://sumire.pbworks.com/w/page/76623227/REQ%20SYS%20458>`_ describes the requirement of documentations:
'requirement of documentations' -> 'documentation requirements'

2019-07-09 21:57 UTC, hassanxp approved these changes
Minor typos spotted, if you have time to fix. Otherwise looks good.

2019-07-10 14:42 UTC, naoyukitamura approved these changes

2019-07-12 14:06 UTC, hassanxp commented on development-management/development_practice.rst
> +PFS Software Development Practice
Practice->Practices, as this document covers a number of practices that developers are encouraged to follow. The filename should also be updated accordingly.

2019-07-13 20:24 UTC, merged